### ISSUE TITLE
execution procedure

### ISSUE THREAD

**Issue by ukunnath** [lx10077/TrGoF#1]
Can you please provide the execution procedure for this code repo ?

**Comment by lx10077** [comment]
Hello, I’ve updated the README.md to include command-line examples. In general, since each file comes with default hyperparameters, you can simply run:

```
python THE_PYTHON_FILE.py
```

**Comment by ukunnath** [comment]
Thank you, i will go through and update in case of any further issues

**Comment by usmanmitchn** [comment]
does it require GPU ? below execution always stuck
python3.12 Step1_watermark_text.py --model facebook/opt-1.3b --c 5 --m 400 --T 1000 --batch_size 10 --all_temp 0.1 0.3 0.5 0.7 
Namespace(method='Gumbel', model='facebook/opt-1.3b', seed=15485863, c=5, batch_size=10, seed_way='noncomm_prf', m=400, T=1000, prompt_tokens=50, buffer_tokens=20, non_wm_temp=0.7, max_seed=100000, norm=1, rt_translate=False, truncate_vocab=8, all_temp=[0.1, 0.3, 0.5, 0.7])
Using 0 GPUs - 0.00 GB allocated per GPU.

**Comment by usmanmitchn** [comment]
does it require GPU ? below execution always stuck
python3.12 Step1_watermark_text.py --model facebook/opt-1.3b --c 5 --m 400 --T 1000 --batch_size 10 --all_temp 0.1 0.3 0.5 0.7
Namespace(method='Gumbel', model='facebook/opt-1.3b', seed=15485863, c=5, batch_size=10, seed_way='noncomm_prf', m=400, T=1000, prompt_tokens=50, buffer_tokens=20, non_wm_temp=0.7, max_seed=100000, norm=1, rt_translate=False, truncate_vocab=8, all_temp=[0.1, 0.3, 0.5, 0.7])
Using 0 GPUs - 0.00 GB allocated per GPU.
